name:                austrian-economics
version:             0.1.0.0
github:             githubuser/austrian-economics
author:             ""
maintainer:          ""
copyright:          ""

extra-source-files:
- README.md
- CHANGELOG.md

description:         A formalization of Austrian Economics in Haskell
license:             MIT
license-file:        LICENSE

# Metadata used when publishing your package
# synopsis:            Short description of your library
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock syntax inside cabal files, it is
# common to point to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/austrian-economics#readme>

#dependencies:
#- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - base >= 4.7 && < 5
  - containers

  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wpartial-fields

tests:
  austrian-economics-test:
    main:                Spec.hs
    source-dirs:        test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - austrian-economics
    - hspec
    - QuickCheck
